version: '3'

services:
  fusionauth:
    container_name: fusionauth
    image: fusionauth/fusionauth-app:1.36.4
    environment:
      DATABASE_URL: jdbc:postgresql://craigmiller160.ddns.net:30001/fusion_auth_practice
      DATABASE_ROOT_USERNAME: postgres_root
      DATABASE_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      FUSIONAUTH_APP_MEMORY: 512M
      FUSIONAUTH_APP_RUNTIME_MODE: production
      FUSIONAUTH_APP_URL: https://fusionauth:9011
      SEARCH_TYPE: database
    ports:
      - 9011:9011
    networks:
      - fusionauth

networks:
  fusionauth:
    driver: bridge