version: '3.5'

services:
  postgres:
    image: postgres:14.5
    container_name: postgres
    networks:
      - fusionauth
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'

  fusionauth:
    container_name: fusionauth
    image: fusionauth/fusionauth-app:1.40.0
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/fusion_auth_practice
      DATABASE_ROOT_USERNAME: user
      DATABASE_ROOT_PASSWORD: password
      FUSIONAUTH_APP_MEMORY: 512M
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_TYPE: database
    ports:
      - 9011:9011
      - 9013:9013
      - 9010:9010
      - 9019:9019
    networks:
      - fusionauth

networks:
  fusionauth:
    driver: bridge